sudo: false
language: python
python:
  - “3.4”

install: pip install -r requirements.txt

# before_script:
#   - psql -c ‘create database wemove_primary;’ -U postgres

script:
  - python3 tests_basic.py
