sudo: false
language: python
python:
  - “3.5”

install: pip install -r requirements.txt

before_script:
  - psql -c ‘create database wemove_primary;’ -U postgres

script:
  - python tests/unit_tests_primary.py
