sudo: false
language: python
python:
  - "3.6"
install: pip install -r requirements.txt

# before_script:
#   - psql -c ‘create database wemove_primary;’ -U postgres

script:
  - python -c "import os; print(os.getcwd())"
  - python test_basic.py
